package by.epam.web.controller;

public enum ActionName {
	DELETE_USER, GET_ALL_USERS, REGISTER, SIGN_IN, SIGN_OUT, ADD_EQUIPMENT, DELETE_EQUIPMENT_BY_ID,
	GET_ALL_EQUIPMENT, CREATE_ORDER, WRONG_REQUEST, ADD_TO_CART, UPDATE_CART, DELETE_FROM_CART, ADD_CART, GET_USER_ITEMS, DELETE_ITEM_BY_ID, SET_EN, SET_RU;
}
